sudo: required

services:
  - docker

language: generic

before_install:
  - docker build -t caff3ine/docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true caff3ine/docker-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-932906077365"
  bucket_path: "docker-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"